<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="9" hostname="LAPTOP-0FD1O0AP" failures="1" tests="1" name="Default test" time="22.585" errors="0" timestamp="2023-02-07T21:04:36 IST">
  <testcase classname="com.qa.Tests.LoginPageTest" name="verifyLogin" time="0.32">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.qa.Tests.LoginPageTest.verifyLogin(LoginPageTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase classname="com.qa.Tests.LoginPageTest" name="verifyErrorMessageForUsername" time="0.0">
    <ignored/>
  </testcase> <!-- verifyErrorMessageForUsername -->
  <testcase classname="com.qa.Tests.LoginPageTest" name="verifyLoginPageURL" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginPageURL -->
  <testcase classname="com.qa.Tests.LoginPageTest" name="verifyUsername" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUsername -->
  <testcase classname="com.qa.Tests.LoginPageTest" name="verifyErrorMessageForWrongCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyErrorMessageForWrongCredentials -->
  <testcase classname="com.qa.Tests.LoginPageTest" name="verifyLoginPageTitle" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginPageTitle -->
  <testcase classname="com.qa.Tests.LoginPageTest" name="verifyPassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyPassword -->
  <testcase classname="com.qa.Tests.LoginPageTest" name="verifyLoginLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginLogoTest -->
  <testcase classname="com.qa.Tests.LoginPageTest" name="verifyBoatLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyBoatLogoTest -->
  <testcase classname="com.qa.Tests.LoginPageTest" name="verifyErrorMessageForPassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyErrorMessageForPassword -->
</testsuite> <!-- Default test -->
